schema_version = "1.0.0"
id = "Clip_Tools"
version = "1.0.0"
name = "Clip Tools"
tagline = "Add a simple tool to the Movie Clip Editor"
maintainer = "Naoki Korematsu" 
type = "add-on"
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
tags = ["Tracking", "Camera", "3D View"]